services:
  # web:
  #   container_name: nginx-container
  #   image: wed-nginx
  #   build:
  #     context: ./
  #     dockerfile: nginx.Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     # - server
  #     - client
  #   networks:
  #     - mynet

  # client:
  #   container_name: client-container
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   restart: always
  #   # ports:
  #   #   - 3000:3000
  #   # depends_on:
  #   #   - server
  #   networks:
  #     - mynet
  #   # environment:
  #   #   - NEXT_PUBLIC_SERVER_URL=http://server:4000
  #   #   - NEXT_PUBLIC_CLIENT_URL=http://client:4000

  # server:
  #   container_name: server-container
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   restart: always
  #   depends_on:
  #     - redis
  #     - postgres
  #   # ports:
  #   #   - 4000:4000
  #   # environment:
  #   #   - CLIENT_URL=http://client:3000
  #   networks:
  #     - mynet

  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
    volumes:
      - ./docker_volumes/cache:/data
    networks:
      - mynet

  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgresdb
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./docker_volumes/postgres:/var/lib/postgresql/data
    networks:
      - mynet

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_VHOST=my-rabbit
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=secret

networks:
  mynet:
    driver: bridge
